# Generated by Django 4.2.26 on 2025-11-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_supportreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='follow_up_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='follow_up_required',
            field=models.BooleanField(default=False),
        ),
    ]
